# Generated by Django 5.1.6 on 2025-02-17 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_task_delete_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=500,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(500)],
            ),
        ),
    ]
